import json

keyword_categories = {
    'beginner': 'Beginner',
    'beginner-friendly': 'Beginner',
    'tutorial': 'Beginner',
    'tutorials': 'Beginner',
    'web-programming': 'Web/Mobile Development',
    'machine-learning': 'Machine Learning',
    'ml': 'Machine Learning',
    'ai': 'Machine Learning',
    'gpt': 'Machine Learning',
    'chatgpt': 'Machine Learning',
    'gemini': 'Machine Learning',
    'internet-of-things': 'Internet of Things',
    'oauth2': 'Internet of Things',
    'smartapp': 'Internet of Things',
    'smartthings': 'Internet of Things',
    'upnp': 'Internet of Things',
    'zigbee': 'Internet of Things',
    'zwave': 'Internet of Things',
    'bootstrap': 'Web/Mobile Development',
    'css': 'Web/Mobile Development',
    'css-framework': 'Web/Mobile Development',
    'html': 'Web/Mobile Development',
    'html5': 'Web/Mobile Development',
    'javascript': 'Web/Mobile Development',
    'sass': 'Web/Mobile Development',
    'scss': 'Web/Mobile Development',
    'vue': 'Web/Mobile Development',
    'vue3': 'Web/Mobile Development',
    'react': 'Web/Mobile Development',
    'nodejs': 'Web/Mobile Development',
    'node': 'Web/Mobile Development',
    'expressjs': 'Web/Mobile Development',
    'django': 'Web/Mobile Development',
    'docker': 'Web/Mobile Development',
    'sdk': 'Web/Mobile Development',
    'server': 'Web/Mobile Development',
    'azure': 'Web/Mobile Development',
    'aspnet': 'Web/Mobile Development',
    'kubernetes': 'Web/Mobile Development',
    'spring-boot': 'Web/Mobile Development',
    'spring': 'Web/Mobile Development',
    'swift': 'Web/Mobile Development',
    'angular': 'Web/Mobile Development',
    'deep-learning': 'Machine Learning',
    'deep-neural-networks': 'Machine Learning',
    'langchain': 'Machine Learning',
    'tensorflow': 'Machine Learning',
    'website': 'Web/Mobile Development',
    'webapp': 'Web/Mobile Development',
    'web': 'Web/Mobile Development',
    'app': 'Web/Mobile Development',
    'flask': 'Web/Mobile Development',
    'oracle': 'Web/Mobile Development',
    'image-generation': 'Machine Learning',
    'image2image': 'Machine Learning',
    'imagenet': 'Machine Learning',
    'data-mining': 'Machine Learning',
    'cloud': 'Cloud Computing',
    'cloud-computing': 'Cloud Computing',
    'aws': 'Cloud Computing',
    'terraform': 'Cloud Computing',
    'flutter': 'Web/Mobile Development',
    'generation': 'Machine Learning',
    'data': 'Data'
}

# Write the dictionary to a JSON file
with open('data/keyword_categories.json', 'w') as file:
    json.dump(keyword_categories, file, indent=4)
